# Generated by Django 3.2.5 on 2021-07-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdf_app', '0003_rename_data_filename_csvdata_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='data_name',
            field=models.CharField(max_length=300),
        ),
    ]
