# Generated by Django 3.2.5 on 2021-07-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdf_app', '0005_alter_csvdata_data_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdata',
            old_name='data_file',
            new_name='data_json',
        ),
    ]
